<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Created At' => 'Создан',
    'ID' => '№',
    'Link' => 'Ссылка',
    'Status' => 'Статус',
    'Text' => 'Текст',
    'Title' => 'Заголовок',
    'Draft' => 'Черновик',
    'Public' => 'Опубликовано',
    'Delete' => 'Удалено',
    'News successfully added' => 'Новость успешно добавлена',
    'Your news sent for moderation' => 'Ваша новость отправлена на модерацию',
    'Suggest news' => 'Предложить новость',
    'News' => 'Новости',
    'Are you sure you want to delete this item?' => 'Удалить новость?',
    'Read more' => 'Читать далее',
];
