<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => '№',
    'Status' => 'Статус',
    'Username' => 'Логин',
    'Active' => 'Активен',
    'Delete' => 'Удалён',
    'Created At' => 'Зарегистрирован',
    'Users' => 'Пользователи',
    'Generate new access token for API' => 'Получить новый токен доступы для API',
    'Failed to generate new token.' => 'Ошибка при генерации нового токена.',
    'Make sure to copy your new personal access token now. You won\'t be able to see it again!' => 'Обязательно скопируйте новый токен доступа. Вы не сможете увидеть его снова!',
    'Access token: {accessToken}' => 'Токен доступа: {accessToken}',
];
